Entity/Post.php
<?php

namespace XLabs\ForumBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use \DateTime;
use XLabs\ForumBundle\Entity\Topic;
use Symfony\Component\Validator\Constraints as Assert;
use XLabs\ResultCacheBundle\Annotations as XLabsResultCache;

/**
 * @ORM\Entity(repositoryClass="XLabs\ForumBundle\Repository\PostRepository")
 * @ORM\Table(name="xlabs_forum_posts")
 * @XLabsResultCache\Clear(onFlush={}, {
 *      @XLabsResultCache\Key(onFlush={"insert", "update", "delete"}, type="literal", method="getXLabsResultCacheKeyForItem"),
 *      @XLabsResultCache\Key(onFlush={"insert", "update", "delete"}, type="prefix", method="getXLabsResultCacheKeyForCollection")
 * })
 */
class Post
{
    const IMAGES_FOLDER = 'posts';
    // Keys used in PostRepository
    const RESULT_CACHE_ITEM_PREFIX = 'xlabs_forum_post_';
    const RESULT_CACHE_ITEM_TTL = 604800; // 1 week
    // Keys used in SearchPost
    const RESULT_CACHE_COLLECTION_PREFIX = 'xlabs_forum_posts_';
    const RESULT_CACHE_COLLECTION_TTL = 3600;

    const STATUS_APPROVED = 0;
    const STATUS_WAITING_FOR_APPROVAL = 1;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\Column(name="title", type="string", length=100, nullable=true, options={"collation": "utf8mb4_unicode_ci"})
     * @Assert\Length(
     *      max = 100,
     *      maxMessage = "The title cannot be longer than {{ limit }} characters"
     * )
     */
    private $title;

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @ORM\Column(name="body", type="text", nullable=true, options={"collation": "utf8mb4_unicode_ci"})
     */
    private $body;

    public function getBody()
    {
        return $this->body;
    }

    public function setBody($body)
    {
        $this->body = $body;
    }

    /**
     * @ORM\Column(name="image", type="string", length=128, nullable=true)
     */
    private $image;

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }

    /**
     * @ORM\Column(name="folder", type="string", length=255, nullable=true)
     */
    protected $folder;

    public function setFolder($folder)
    {
        $this->folder = $folder;
    }

    public function getFolder()
    {
        return $this->folder;
    }

    /**
     * @ORM\Column(name="creationdate", type="datetime", nullable=false)
     */
    private $creationdate;

    public function getCreationdate()
    {
        return $this->creationdate;
    }

    public function setCreationdate($creationdate)
    {
        $this->creationdate = $creationdate;
    }

    /**
     * @ORM\Column(name="publishdate", type="datetime", nullable=true)
     */
    private $publishdate;

    public function getPublishdate()
    {
        return $this->publishdate;
    }

    public function setPublishdate($publishdate)
    {
        if($publishdate instanceof DateTime)
        {
            $publishdate = $publishdate->format('d-m-Y H:i:s');
        }
        if(is_array($publishdate) && array_key_exists('publishdate_date', $publishdate)) // patch for the compound form data upon 'PATCH' request
        {
            $publishdate = $publishdate['publishdate_date'];
        }
        if($publishdate)
        {
            // Patch for disabled datepicker
            $this->publishdate = DateTime::createFromFormat('d-m-Y H:i:s', $publishdate);
        }
    }

    /*
     * @ORM\Column(name="content_type", type="smallint", nullable=false)
     */
    /*private $content_type;

    public function getContentType()
    {
        return $this->content_type;
    }

    public function setContentType($content_type)
    {
        $this->content_type = $content_type;
    }*/

    /*
     * @ORM\Column(name="visibility", type="smallint", nullable=false)
     */
    /*private $visibility;

    public function getVisibility()
    {
        return $this->visibility;
    }

    public function setVisibility($visibility)
    {
        $this->visibility = $visibility;
    }*/

    /**
     * @ORM\Column(name="status", type="integer", nullable=false)
     */
    private $status;

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @ORM\Column(name="hidden", type="boolean", nullable=false)
     */
    private $hidden;

    public function getHidden()
    {
        return $this->hidden;
    }

    public function setHidden($hidden)
    {
        $this->hidden = $hidden;
    }

    public function isHidden()
    {
        return $this->getHidden();
    }

    /*
     * Unmapped, for admin form purposes
     */
    protected $preserve_html;

    public function getPreserveHTML()
    {
        return $this->preserve_html;
    }

    public function setPreserveHTML($preserve_html)
    {
        $this->preserve_html = $preserve_html;
    }

    /*
     * @ORM\Column(name="depth", type="integer", nullable=false)
     */
    /*protected $depth = 0;

    public function getDepth()
    {
        return $this->depth;
    }

    public function setDepth($depth)
    {
        $this->depth = $depth;
    }*/

    /*
     * @ORM\Column(name="ancestors", type="text", nullable=true)
     */
    /*protected $ancestors;

    public function getAncestors()
    {
        return $this->ancestors ? array_filter(explode('/', $this->ancestors)) : array();
    }

    public function setAncestors(array $ancestors)
    {
        $this->ancestors = '/'.implode('/', $ancestors).'/';
        $this->depth = count($ancestors);
    }

    public function addAncestor($ancestor_id)
    {
        $ancestors = $this->getAncestors();
        $ancestors[] = $ancestor_id;
        $this->setAncestors($ancestors);
    }*/

    /**
     * @ORM\ManyToOne(targetEntity="XLabs\ForumBundle\Entity\Post", inversedBy="replies")
     * @ORM\JoinColumn(name="thread_id", referencedColumnName="id")
     */
    private $thread;

    public function getThread()
    {
        return $this->thread;
    }

    public function setThread($thread)
    {
        $this->thread = $thread;
    }

    /**
     * @ORM\OneToMany(targetEntity="XLabs\ForumBundle\Entity\Post", mappedBy="thread", orphanRemoval=true)
     */
    private $replies;

    /*
     * Mapped through event listener
     */
    protected $author;

    public function getAuthor()
    {
        return $this->author;
    }

    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @ORM\ManyToOne(targetEntity="XLabs\ForumBundle\Entity\Topic", inversedBy="posts")
     * @ORM\JoinColumn(name="topic_id", referencedColumnName="id")
     **/
    private $topic;

    public function getTopic()
    {
        return $this->topic;
    }

    public function setTopic($topic)
    {
        $this->topic = $topic;
    }

    /**
     * @ORM\ManyToOne(targetEntity="XLabs\ForumBundle\Entity\Post")
     * @ORM\JoinColumn(name="quoted_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $quoted;

    public function getQuoted()
    {
        return $this->quoted;
    }

    public function setQuoted($quoted)
    {
        $this->quoted = $quoted;
    }

    public function __construct()
    {
        $this->creationdate = new DateTime();
        $this->publishdate = new DateTime();
        $this->hidden = false;
        $this->folder = $this->creationdate->format('dmYHis');
        $this->replies = new ArrayCollection();
        $this->preserve_html = false;
    }

    public function __get($name)
    {
        return $this->$name;
    }
    public function __set($name, $value)
    {
        $this->$name = $value;
    }

    public function getXLabsResultCacheKeyForItem()
    {
        return array(
            $this::RESULT_CACHE_ITEM_PREFIX.$this->getId(),
            $this::RESULT_CACHE_ITEM_PREFIX.$this->getId().'_hydration',
        );
    }

    public function getXLabsResultCacheKeyForCollection()
    {
        $keys = array(
            $this::RESULT_CACHE_COLLECTION_PREFIX,
            Topic::RESULT_CACHE_COLLECTION_PREFIX,
        );
        return $keys;
    }
}

Resources/views/ContentBlock/block.html.twig
{% set aParams = aParams is defined ? aParams : {} %}
{% if aParams.results_template is not  defined %}
    {% set aParams = aParams|merge({'results_template': '@XLabsForum/ContentBlock/results.html.twig'}) %}
{% endif %}
{% if aParams.pagination_template is not  defined %}
    {% set aParams = aParams|merge({'pagination_template': '@XLabsForum/ContentBlock/pagination.html.twig'}) %}
{% endif %}
{% if aParams.container_id is not defined %}
    {% set aParams = aParams|merge({'container_id': random()}) %}
{% endif %}
{% if aParams.ajax_pagination is defined %}
    {% set aParams = aParams|merge({'show_pagination': true}) %}
{% endif %}
{% set aParams = aParams.container_id is defined ? aParams|merge({'container_id': aParams.container_id}) : aParams|merge({'container_id': random()}) %}

<div class="_xlabs_results_wrapper" data-container-id="{{ aParams.container_id }}" data-ajax-path="{{ path('xlabs_forum_admin_load_results') }}" data-ajax-params="{{ aParams|json_encode() }}" data-original-params="{{ aParams|json_encode() }}">
    <div class="_xlabs_results">
        {{ render(controller('XLabsForumBundle:ForumAdmin:renderResults', {
            'aParams': aParams
        })) }}
    </div>
</div>

<script>
    {% if aParams.ajax_pagination is defined and aParams.ajax_pagination %}
        // Pagination buttons
        $('[data-container-id="{{ aParams.container_id }}"] ._xlabs_results').on('click', '.pageBtn', function(e){
            e.preventDefault();
            let btn = $(this);
            let aParams_container = $('[data-container-id="{{ aParams.container_id }}"]');
            let aParams = JSON.parse(aParams_container.attr('data-ajax-params'));

            aParams.page = btn.attr('data-page');
            updateContentBlockResults(aParams_container, aParams);
        });

        /*function findContent()
        {
            // create form and submit it to send post parameters
            let aParams_container = $('[data-container-id="{{ aParams.container_id }}"]');
            let aParams = JSON.parse(aParams_container.attr('data-ajax-params'));
            let form = $('<form />');
            //if(!href)
            //{
            //    href = getCleanURI();
            //    if(aParams.search_terms)
            //    {
            //        href += '?s=' + aParams.search_terms;
            //    }
            //}
            form.attr({
                action: href,
                method: 'post',
                enctype: 'multipart/form-data'
            }).css('display', 'none');
            $('body').append(form);
            //let form_data = new FormData(form.get(0));
            //form_data.append('aParams', JSON.stringify(aParams));
            form.append($('<input/>', {
                type: 'hidden',
                name: 'aParams',
                value: JSON.stringify(aParams)
            }));
            form.submit();
        }*/
    {% endif %}
</script>

Resources/views/ContentBlock/headerJS.html.twig
<script>
    /****************************************************************************************/
    /*                         Content block common JS                                      */
    /****************************************************************************************/
    function updateContentBlockResults(aParams_container, updated_aParams)
    {
        aParams_container.attr('data-ajax-params', JSON.stringify(updated_aParams));
        aParams_container.css('opacity', '.6');
        $.ajax({
            url: aParams_container.attr('data-ajax-path'),
            data: {
                aParams: updated_aParams
            },
            type: 'post',
            dataType: 'html',
            success: function(data){
                aParams_container.find('._xlabs_results').html(data);
                aParams_container.css('opacity', '1');
            },
            error: function(){
                aParams_container.css('opacity', '1');
            }
        });
    }
</script>

Resources/views/ContentBlock/pagination.html.twig
{% if pageCount > 1 %}
    <div class="paginationArea">
        <div class="left">
            {% if first is defined and current != first %}
                <a href="{{ path(route, query|merge({(pageParameterName): first})) }}" data-page="{{ first }}" class="pageBtn" title="first"><i class="fas fa-chevron-left"></i><i class="fas fa-chevron-left"></i></a>
            {% endif %}

            {% if previous is defined %}
                <a href="{{ path(route, query|merge({(pageParameterName): previous})) }}" data-page="{{ previous }}" class="pageBtn" title="previous"><i class="fas fa-chevron-left"></i></a>
            {% endif %}
        </div>
        <div class="center">
            {% for page in pagesInRange %}
                {% if page != current %}
                    <a href="{{ path(route, query|merge({(pageParameterName): page})) }}" data-page="{{ page }}" class="pageBtn" title="Go to {{ page }}">{{ page }}</a>
                {% else %}
                    <a class="highlight">{{ page }}</a>
                {% endif %}
            {% endfor %}
        </div>
        <div class="right">
            {% if next is defined %}
                <a href="{{ path(route, query|merge({(pageParameterName): next})) }}" data-page="{{ next }}" class="pageBtn" title="next"><i class="fas fa-chevron-right"></i></a>
            {% endif %}

            {% if last is defined and current != last %}
                <a href="{{ path(route, query|merge({(pageParameterName): last})) }}" data-page="{{ last }}" class="pageBtn" title="last"><i class="fas fa-chevron-right"></i><i class="fas fa-chevron-right"></i></a>
            {% endif %}
        </div>
    </div>
{% endif %}

Resources/views/ContentBlock/results.html.twig
{% if aParams.search_terms is defined and aParams.search_terms and aParams.page == 1 %}
    <div class="search_filters">
        <span>Search results for: </span><b>{{ aParams.search_terms }}</b>
    </div>
{% endif %}

{% if aParams.double_pagination is defined and aParams.double_pagination %}
    {% if pagination %}
        {% if aParams.show_pagination is defined and aParams.show_pagination %}
            <div class="_pagination" style="{{ aParams.infinite_scroll is defined and aParams.infinite_scroll ? 'display: none;' : '' }}">
                {{ knp_pagination_render(pagination, aParams.pagination_template) }}
            </div>
        {% endif %}
    {% endif %}
{% endif %}

{% if results|length %}
    {% if aParams.renderMode is defined and aParams.renderMode == 'table' %}
        <table class="_table">
            {% if aParams.tableHeaders is defined %}
                <tr>
                    {% for tableHeader in aParams.tableHeaders %}
                        {% set colWidth = aParams.tableWidths is defined ? aParams.tableWidths[loop.index0] : '' %}
                        <th {{ colWidth ? ('style="width: '~colWidth~'"')|raw : '' }}>{{ tableHeader|capitalize }}</th>
                    {% endfor %}
                </tr>
            {% endif %}
            {% for result in results %}
                {% include aParams.item_template with {
                    'item': result,
                    'aParams': aParams
                } %}
            {% endfor %}
        </table>
    {% else %}
        <div class="_forum_{{ aParams.contentType }}">
            {% for result in results %}
                <div class="_forum_{{ aParams.contentType }}_item">
                    {% include aParams.item_template with {
                        'item': result,
                        'aParams': aParams
                    } %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% else %}
    {% if aParams.remove_block_if_no_results is defined and aParams.remove_block_if_no_results %}
        {% if aParams.container_id is defined and aParams.container_id %}
            <script>
                $('div[data-container-id="{{ aParams.container_id }}"]').remove();
            </script>
        {% endif %}
    {% elseif aParams.hide_block_if_no_results is defined and aParams.hide_block_if_no_results %}
        {% if aParams.container_id is defined and aParams.container_id %}
            <script>
                $('div[data-container-id="{{ aParams.container_id }}"]').hide();
            </script>
        {% endif %}
    {% elseif aParams.page == 1 %}
        {% if aParams.no_results_template is defined and aParams.no_results_template %}
            {% include aParams.no_results_template %}
        {% else %}
            <div class="_noContent">
                {#<span>No results to show ;(</span>#}
                <img src="{{ asset('bundles/xlabsforum/images/no_results_found.webp') }}" style="opacity: .8;" />
            </div>
        {% endif %}
    {% endif %}
{% endif %}

{% if pagination %}
    {% if aParams.show_pagination is defined and aParams.show_pagination %}
        <div class="_pagination" style="{{ aParams.infinite_scroll is defined and aParams.infinite_scroll ? 'display: none;' : '' }}">
            {{ knp_pagination_render(pagination, aParams.pagination_template) }}
        </div>
    {% endif %}
{% endif %}